# Generated by Django 4.2.6 on 2024-04-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customers',
        ),
    ]
